name: CI — Deploy frontend to S3 + CloudFront

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1
  S3_BUCKET: recipe-bot-frontend
  CLOUDFRONT_ID: dc61h2yo7vgoh.cloudfront.net   # <-- replace with your real distribution ID

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          if ! grep -q "<html" frontend/dashboard.html; then
            echo "dashboard.html missing <html> tag"
            exit 1
          fi

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload dashboard.html to S3
        run: |
          aws s3 cp frontend/dashboard.html s3://$S3_BUCKET/dashboard.html --acl public-read

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_ID \
            --paths "/dashboard.html"
